"""Render docs/data_sources.md from config/sources.yaml, config/evidence_docs.yaml and data/manifest.json.

    pixi run docs-sources

Generated rather than hand-written, so the source list in the docs can never drift from the config.
"""

from __future__ import annotations

import json
from collections import defaultdict

from rtl.settings import MANIFEST_PATH, REPO_ROOT, load_yaml, sources

OUT = REPO_ROOT / "docs" / "data_sources.md"


def main() -> None:
    manifest = json.loads(MANIFEST_PATH.read_text()) if MANIFEST_PATH.exists() else {}
    files, size = defaultdict(int), defaultdict(int)
    for e in manifest.values():
        files[e["source_id"]] += 1
        size[e["source_id"]] += e["bytes"]

    lines = ["# Data sources", "",
             "*Generated by `pixi run docs-sources` from `config/sources.yaml`, `config/evidence_docs.yaml` and "
             "`data/manifest.json`. Don't edit by hand.*", "",
             "Role: **feature** = model input; **weak_label** = labelling evidence; **validation** = never a model "
             "input, used only to check results; **evidence** = source of appliance-profile parameters. "
             "Restricted sources are held locally and never redistributed.", "",
             "| id | source | owner | role | access | licence | status | files in manifest |",
             "|---|---|---|---|---|---|---|---|"]
    for sid, s in sources().items():
        n = files.get(sid, 0)
        got = f"{n} ({size[sid] / 1e6:,.0f} MB)" if n else "-"
        lines.append(f"| `{sid}` | {s.get('name', '')} | {s.get('owner', '')} | {s.get('role', '')} | "
                     f"{s.get('access', '')} | {s.get('licence', '')} | {s.get('status', '')} | {got} |")

    ev = load_yaml("evidence_docs.yaml")
    docs = ev.get("documents", ev)
    items = docs.items() if isinstance(docs, dict) else [(d.get("doc_id"), d) for d in docs]
    lines += ["", "## Evidence corpus (appliance profiles and validation anchors)", "",
              "| doc_id | title | publisher | year | status |", "|---|---|---|---|---|"]
    for doc_id, d in items:
        lines.append(f"| `{doc_id}` | {d.get('title', '')} | {d.get('publisher', '')} | {d.get('year', '')} | "
                     f"{d.get('status', '')} |")
    lines += ["", f"Manifest: {len(manifest)} files, {sum(size.values()) / 1e9:.1f} GB in total."]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{len(sources())} sources, {len(items)} evidence docs -> {OUT}")


if __name__ == "__main__":
    main()
